services:
  - type: web
    name: automacoes-mobile-mercado
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --workers 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: FIREBASE_CREDENTIALS_JSON
        sync: false
      - key: FLASK_DEBUG
        value: "0"
      - key: LOG_TO_FILE
        value: "0"